"""empty message

Revision ID: 331edc1149a7
Revises: b24d2d3da6e2
Create Date: 2026-05-28 14:53:13.610067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '331edc1149a7'
down_revision: Union[str, Sequence[str], None] = 'b24d2d3da6e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal_logs', sa.Column('created_at', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False))
    op.drop_column('goal_logs', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal_logs', sa.Column('date', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=False))
    op.drop_column('goal_logs', 'created_at')
    # ### end Alembic commands ###
