"""empty message

Revision ID: 37aec6df6289
Revises: 76c4f02acfe4
Create Date: 2026-06-06 16:43:15.876878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision: str = '37aec6df6289'
down_revision: Union[str, Sequence[str], None] = '76c4f02acfe4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(text("ALTER TABLE goals ALTER COLUMN start_date SET DEFAULT CURRENT_DATE;"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(text("ALTER TABLE goals ALTER COLUMN start_date DROP DEFAULT;"))
    # ### end Alembic commands ###
