"""empty message

Revision ID: 472b3f9b5819
Revises: 331edc1149a7
Create Date: 2026-05-28 14:55:45.601843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision: str = '472b3f9b5819'
down_revision: Union[str, Sequence[str], None] = '331edc1149a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(text("ALTER TABLE goal_logs ADD CONSTRAINT goal_logs_created_at_check CHECK (created_at <= CURRENT_DATE);"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(text("ALTER TABLE goal_logs DROP CONSTRAINT goal_logs_created_at_check;"))
    # ### end Alembic commands ###
