"""empty message

Revision ID: 7125b895c769
Revises: 37aec6df6289
Create Date: 2026-06-07 12:07:58.956138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7125b895c769'
down_revision: Union[str, Sequence[str], None] = '37aec6df6289'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'currency',
               existing_type=sa.CHAR(length=3),
               type_=sa.Enum('USD', 'BYN', 'RUB', name='currency', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'USD'::bpchar"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'currency',
               existing_type=sa.Enum('USD', 'BYN', 'RUB', name='currency', native_enum=False),
               type_=sa.CHAR(length=3),
               existing_nullable=False,
               existing_server_default=sa.text("'USD'::bpchar"))
    # ### end Alembic commands ###
