"""empty message

Revision ID: 76c4f02acfe4
Revises: f5cc08763c48
Create Date: 2026-06-05 22:50:12.783811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision: str = '76c4f02acfe4'
down_revision: Union[str, Sequence[str], None] = 'f5cc08763c48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(text("ALTER TABLE users ALTER COLUMN currency SET DEFAULT 'USD';"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(text("ALTER TABLE users ALTER COLUMN currency DROP DEFAULT;"))
    # ### end Alembic commands ###
