"""empty message

Revision ID: 9329279fec92
Revises: 7125b895c769
Create Date: 2026-06-07 14:50:08.589268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision: str = '9329279fec92'
down_revision: Union[str, Sequence[str], None] = '7125b895c769'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(text("ALTER TABLE goal_logs DROP CONSTRAINT goal_logs_type_check;"))
    op.execute(text("ALTER TABLE goal_logs ADD CONSTRAINT goal_logs_type_check CHECK (type IN ('deposit', 'withdraw'));"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
