"""empty message

Revision ID: bfa394ac9b3f
Revises: 717d9e20f611
Create Date: 2026-06-09 18:47:36.100131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfa394ac9b3f'
down_revision: Union[str, Sequence[str], None] = '717d9e20f611'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('goal_logs', 'type',
               existing_type=sa.CHAR(length=8),
               type_=sa.String(length=8),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('goal_logs', 'type',
               existing_type=sa.String(length=8),
               type_=sa.CHAR(length=8),
               existing_nullable=False)
    # ### end Alembic commands ###
