"""empty message

Revision ID: f0919e2eb1dd
Revises: 849639ab6ff9
Create Date: 2026-05-23 17:06:15.738369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision: str = 'f0919e2eb1dd'
down_revision: Union[str, Sequence[str], None] = '849639ab6ff9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(text("ALTER TABLE goals ALTER COLUMN description SET DEFAULT NULL;"))
    op.execute(text("ALTER TABLE goals ALTER COLUMN link SET DEFAULT NULL;"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(text("ALTER TABLE goals ALTER COLUMN description SET DEFAULT 'Empty';"))
    op.execute(text("ALTER TABLE goals ALTER COLUMN link SET DEFAULT 'Empty';"))
    # ### end Alembic commands ###
