"""empty message

Revision ID: f5cc08763c48
Revises: 472b3f9b5819
Create Date: 2026-06-05 22:02:24.361425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision: str = 'f5cc08763c48'
down_revision: Union[str, Sequence[str], None] = '472b3f9b5819'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_refresh_tokens',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.add_column('goal_logs', sa.Column('currency', sa.CHAR(length=3), nullable=False))
    op.add_column('goals', sa.Column('target_currency', sa.CHAR(length=3), nullable=False))
    op.execute(text("ALTER TABLE goals DROP CONSTRAINT goals_end_date_check;"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goals', 'target_currency')
    op.drop_column('goal_logs', 'currency')
    op.drop_table('user_refresh_tokens')
    op.execute("ALTER TABLE goals ADD CONSTRAINT goals_end_date_check CHECK ('end_date >= CURRENT_DATE');")
    # ### end Alembic commands ###
